name: Qitmeer Java integration library testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run test
      run: ./gradlew test
