name: Qitmeer Java integration library testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Checkout Qitmeer
        uses: actions/checkout@v2
        with:
          repository: qitmeer/qitmeer
          ref: 0.10.6-rel
          path: qitmeer

      - name: Build qitmeer
        run: cd qitmeer && make all

      - name: Run Qitmeer
        run: cd qitmeer/build/bin && nohup ./qitmeer --privnet --rpclisten 127.0.0.1:1234 --rpcuser test --rpcpass test --modules=miner --modules=qitmeer --miningaddr=RmQb2VrPtd9nftMvKtRMxN297dzN5VydmMJ > run.log 2>&1 &

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run test
        run: ./gradlew test
